name: Build AMI and Deploy Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      # Step 1: Checkout NexusProject repo
      - name: Checkout NexusProject repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          path: nexusproject

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Install prerequisites
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl jq python3-pip
          pip3 install ansible

      # Step 4: Run Ansible playbook
      - name: Run Ansible Playbook
        working-directory: nexusproject/step2-ansible
        run: |
          ansible-playbook -i inventory install_nexus.yml

      # Step 5: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Step 6: Install Packer
      - name: Install Packer
        run: |
          curl -LO https://releases.hashicorp.com/packer/1.9.4/packer_1.9.4_linux_amd64.zip
          unzip packer_1.9.4_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          packer version

      # Step 7: Build AMI with Packer
      - name: Build AMI
        working-directory: nexusproject/step3-packer
        run: |
          packer init .
          packer build -force -machine-readable .

      # Step 8: Get the AMI ID from Packer output
      - name: Get AMI ID
        id: ami
        run: |
          AMI_ID=$(packer inspect -json ./nexus.pkr.hcl | jq -r '.builds[-1].artifact_id' | cut -d ':' -f2)
          echo "ami_id=$AMI_ID" >> $GITHUB_ENV

      # Step 9: Apply Terraform
      - name: Apply Terraform
        working-directory: nexusproject/step4-terraform
        run: |
          terraform init
          terraform apply -auto-approve -var="ami_id=${{ env.ami_id }}" -var="key_name=my-laptop-key" -var="region=${{ env.AWS_REGION }}"